version: '2'
services:
  nginx:
    image: erayarslan/nginx:prod
    links:
      - api1:api1
      - api2:api2
      - api3:api3
    ports:
      - 80:80
  prerender:
    image: erayarslan/prerender:prod
    ports:
      - 3000:3000
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb:/data/db
  web:
    image: erayarslan/web:prod
    environment:
      - SOZLUK_ENV=prod
    ports:
      - 1337:1337
  api1:
    image: erayarslan/api:prod
    environment:
      - SOZLUK_ENV=prod
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
  api2:
    image: erayarslan/api:prod
    environment:
      - SOZLUK_ENV=prod
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
  api3:
    image: erayarslan/api:prod
    environment:
      - SOZLUK_ENV=prod
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db