version: '2'
services:
  prerender:
    image: erayarslan/prerender:prod
    ports:
      - 3000:3000
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb:/data/db
  web:
    image: erayarslan/web:prod
    environment:
      - SOZLUK_API_URL=http://thisistest.site/service/proxy/api/v1
    ports:
      - 1337:1337
  api:
    image: erayarslan/api:prod
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
