version: '3'
services:
  backup:
    image: erayarslan/sozluk-backup:prod
    volumes:
      - ./shared/backup:/app/backups
      - ./shared/confs/backup/prod.json:/app/confs/prod.json
    environment:
      - SOZLUK_ENV=${SOZLUK_ENV}
    links:
      - db
    depends_on:
      - db
  nginx:
    image: erayarslan/nginx:prod
    volumes:
      - ./shared/ssl:/ssl
    links:
      - api:api
      - web:web
      - prerender:prerender
    ports:
      - 80:80
      - 443:443
  prerender:
    image: erayarslan/prerender:prod
    ports:
      - 3000:3000
  db:
    image: mongo:3.6.3
    ports:
      - 27017:27017
    volumes:
      - ./shared/db:/data/db
  web:
    image: erayarslan/web:prod
    environment:
      - SOZLUK_ENV=${SOZLUK_ENV}
    ports:
      - 1337:1337
  api:
    image: erayarslan/api:prod
    restart: always
    environment:
      - SOZLUK_ENV=${SOZLUK_ENV}
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./shared/confs/api/prod.json:/app/confs/prod.json
